// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bf8_7Kwy0tZdBMLnMy3_97RebO89x7M',
    appId: '1:9882828577:web:b9759b374cae6def9dc860',
    messagingSenderId: '9882828577',
    projectId: 'tacg-portal',
    authDomain: 'tacg-portal.firebaseapp.com',
    storageBucket: 'tacg-portal.firebasestorage.app',
    measurementId: 'G-WGP316BVWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS26QbGXBa0lfjWogfsHhlhAFa9HujENo',
    appId: '1:9882828577:android:505aa090fc360f1b9dc860',
    messagingSenderId: '9882828577',
    projectId: 'tacg-portal',
    storageBucket: 'tacg-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMU3HFT148bhGosbxSCdjCkLAan4zasHA',
    appId: '1:9882828577:ios:6f5e74cebbd95c6d9dc860',
    messagingSenderId: '9882828577',
    projectId: 'tacg-portal',
    storageBucket: 'tacg-portal.firebasestorage.app',
    iosBundleId: 'com.example.tacgportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMU3HFT148bhGosbxSCdjCkLAan4zasHA',
    appId: '1:9882828577:ios:6f5e74cebbd95c6d9dc860',
    messagingSenderId: '9882828577',
    projectId: 'tacg-portal',
    storageBucket: 'tacg-portal.firebasestorage.app',
    iosBundleId: 'com.example.tacgportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6bf8_7Kwy0tZdBMLnMy3_97RebO89x7M',
    appId: '1:9882828577:web:ef4ab5b296cb8f9b9dc860',
    messagingSenderId: '9882828577',
    projectId: 'tacg-portal',
    authDomain: 'tacg-portal.firebaseapp.com',
    storageBucket: 'tacg-portal.firebasestorage.app',
    measurementId: 'G-HPLGKLZZW5',
  );
}
